# Numpy

> Numpy

In [ ]:
#| default_exp num

## Import Numpy

In [ ]:
#|eval: false
!pip list | grep numpy

numpy                         1.23.5


In [ ]:
import numpy as np 

## Creating Numpy Arrays

### Python sequences to NumPy Arrays

In [ ]:
a1D = np.array([1, 2, 3, 4])

a2D = np.array([[1, 2], [3, 4]])

a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

a1D, a2D, a3D

(array([1, 2, 3, 4]),
 array([[1, 2],
        [3, 4]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [ ]:
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

### Intrinsic NumPy array creation functions

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
np.vander(np.linspace(0, 2, 5), 3)

array([[0.  , 0.  , 1.  ],
       [0.25, 0.5 , 1.  ],
       [1.  , 1.  , 1.  ],
       [2.25, 1.5 , 1.  ],
       [4.  , 2.  , 1.  ]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [ ]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Replicating, joining, or mutating existing arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a[:2]

b += 1

print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [ ]:
a = np.array([1, 2, 3, 4])

b = a[:2].copy()

b += 1

print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [ ]:
A = np.ones((2, 2))

B = np.eye(2, 2)

C = np.zeros((2, 2))

D = np.diag((-3, -4))

np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

## Indexing

### Basic indexing

In [ ]:
x = np.arange(10)
x,x[2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 2)

In [ ]:
x[-2]

8

In [ ]:
x.shape = (2, 5)  # now x is 2-dimensional

x, x[1, 3]

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 8)

In [ ]:
x[0], x[0][2]

(array([0, 1, 2, 3, 4]), 2)

#### Slicing and striding

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[1:7:2]

array([1, 3, 5])

In [ ]:
x[-2:10]

array([8, 9])

In [ ]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [ ]:
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

x.shape, x[1:2]

((2, 3, 1),
 array([[[4],
         [5],
         [6]]]))

#### Dimensional indexing tools

In [ ]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [ ]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### Advanced indexing

In [ ]:
x = np.arange(10, 1, -1)

In [ ]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
y = np.arange(35).reshape(5, 7)

y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [ ]:
y[np.array([0, 2, 4]), 1]

array([ 1, 15, 29])

In [ ]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [ ]:
x = np.array([[ 0,  1,  2],

              [ 3,  4,  5],

              [ 6,  7,  8],

              [ 9, 10, 11]])

rows = np.array([[0, 0],

                 [3, 3]], dtype=np.intp)

columns = np.array([[0, 2],

                    [0, 2]], dtype=np.intp)

x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
rows = np.array([0, 3], dtype=np.intp)

columns = np.array([0, 2], dtype=np.intp)

rows[:, np.newaxis]

array([[0],
       [3]])

In [ ]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])

x[~np.isnan(x)]

array([1., 2., 3.])

In [ ]:
x = np.array([1., -1., -2., 3])

x[x < 0] += 20

x

array([ 1., 19., 18.,  3.])

In [ ]:
x = np.arange(35).reshape(5, 7)

b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [ ]:
b[:, 5]

array([False, False, False,  True,  True])

In [ ]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
x = np.array([[ 0,  1,  2],

              [ 3,  4,  5],

              [ 6,  7,  8],

              [ 9, 10, 11]])

rows = (x.sum(-1) % 2) == 0

rows

array([False,  True, False,  True])

In [ ]:
columns = [0, 2]

x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [ ]:
rows = rows.nonzero()[0]

x[rows[:, np.newaxis], columns]

array([[ 3,  5],
       [ 9, 11]])

In [ ]:
x = np.arange(30).reshape(2, 3, 5)

x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
b = np.array([[True, True, False], [False, True, True]])

x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
y = np.arange(35).reshape(5,7)

y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [ ]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [ ]:
x = np.array([[ 0,  1,  2],

              [ 3,  4,  5],

              [ 6,  7,  8],

              [ 9, 10, 11]])

x[1:2, 1:3]

array([[4, 5]])

In [ ]:
x[1:2, [1, 2]]

array([[4, 5]])

In [ ]:
x = np.arange(35).reshape(5, 7)

b = x > 20

b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [ ]:
x[b[:, 5], 1:3]

array([[22, 23],
       [29, 30]])

### Field Access

In [ ]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [ ]:
x['a'].shape, x['b'].shape

((2, 2), (2, 2, 3, 3))

In [ ]:
x['a'].dtype, x['b'].dtype

(dtype('int32'), dtype('float64'))

### Assigning values to indexed arrays

In [ ]:
x = np.arange(10)

x[2:7] = 1

In [ ]:
x[2:7] = np.arange(5)

In [ ]:
x[1] = 1.2

x[1]

1

In [ ]:
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [ ]:
x[np.array([1, 1, 3, 1])] += 1

x

array([ 0, 11, 20, 31, 40])

### Dealing with variable numbers of indices within programs

In [ ]:
z = np.arange(81).reshape(3, 3, 3, 3)

indices = (1, 1, 1, 1)

z[indices]

40

In [ ]:
indices = (1, 1, 1, slice(0, 2))  # same as [1, 1, 1, 0:2]

z[indices]

array([39, 40])

In [ ]:
indices = (1, Ellipsis, 1)  # same as [1, ..., 1]

z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [ ]:
z[[1, 1, 1, 1]]  # produces a large array

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [ ]:
z[(1, 1, 1, 1)]  # returns a single value

40

## I/O with Numpy